name: YouTube Short Upload

# Trigger manually or on schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Optional: run daily at 12:00 UTC

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install moviepy gTTS google-api-python-client google-auth google-auth-oauthlib

    - name: Run video generation and upload
      env:
        YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        YOUTUBE_ACCESS_TOKEN: ${{ secrets.YOUTUBE_ACCESS_TOKEN }}
      run: |
        python generate_and_upload.py
