name: Generate and Upload YouTube Short

on:
  workflow_dispatch:
    # Manual trigger
  schedule:
    - cron: "0 0 * * *"  # optional daily run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Run script
      env:
        YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        TTS: ${{ secrets.TTS }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python generate_and_upload.py
